name: Compile .gma
description: "Compile a Garry's Mod addon into a .gma file using gmad"
on: [push]

inputs:
  gma-name:
    description: 'The name of the resulting .gma file'
    default: '${{GITHUB_REPOSITORY#*/}}.gma'

runs:
  using: "composite"
  image: mattjeanes/gmad
  steps:
    - uses: actions/checkout@v4
      path: 'repo/'
    - run: gmad create -folder "${{ GITHUB_WORKSPACE }}/repo/" -out "${{ GITHUB_WORKSPACE }}/${{ inputs.gma-name }}"
    - uses: actions/upload-artifact@v3
      with:
        name: gma-file
        path: ${{ GITHUB_WORKSPACE }}/${{ inputs.gma-name }}
