on:
  push:
    branches:
      - stable
      - beta
      - alpha
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x.x"
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g
      - run: npx semantic-release
